### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by csibbitt**

### CODE REVIEW

**Comment by csibbitt** [comment]
https://github.com/infrawatch/python-observabilityclient/pull/3 is better, I'm just recording my most recent attempt to get this working. I'll look closer at #3 and contribute there once I actually get it to work again

**Comment by csibbitt** [comment]
FWIW this still doesn't work for me (it has in the past, though?). The instructions seem right, and the ansible runs just fine, but my prometheus_agent pod is crashlooping with this:

```
ts=2022-12-01T18:58:43.747Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
ts=2022-12-01T18:58:43.747Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: no such file or directory"
```

The problem is probably osp-observability-ansible, but just reporting my progress trying to get this working still.

**Comment by csibbitt** [comment]
See: https://github.com/infrawatch/osp-observability-ansible/pull/16

**Comment by csibbitt** [comment]
Abandoning in favor of #3

**Comment by leifmadsen** [comment]
Can I push the _Delete branch_ button on this?

**Pull request closed without merging**
