### PR TITLE
Basic set of docs

### PR DESCRIPTION
**Pull request by leifmadsen**
Basic set of docs to get an environment up and running. Sparse on
details, but wanted to capture the core elements. I wrote this in
markdown since that's what I know. Can convert to reStructuredText in a
separate commit if necessary.

### CODE REVIEW

**Comment by leifmadsen** [comment]
This is a working PR to capture the discussions and installation quirks/notes from https://github.com/infrawatch/python-observabilityclient/pull/1

I'm working through the discussion items and capturing the commands required to have a working deployment. My development environment is an upstream TripleO master (Zed) standalone environment, originally setup for autoscaling deployment. That should not interfere with this work though.

Will continue to work this tomorrow, but I got as far as running:

```
[stack@standalone ~]$ openstack observability setup prometheus_agent --config ./test_params.yaml
```

It fails because I didn't define the `prometheus_remote_write`. Next steps is to define that, get all the items running (in expected failure state) and complete the first round of development installation documentation, working via #1.

**Comment by leifmadsen** [comment]
@paramite you mention in PR 1 that a way to dump all the tripleo env vars to stdout(?) is possible. Do you have an example how that gets done? I'd like to add it to the development docs.

CC: @mgirgisf

**Comment by paramite** [comment]
> @paramite you mention in PR 1 that a way to dump all the tripleo env vars to stdout(?) is possible. 

You can run `grep -r '*' /etc/puppet/hieradata/` to get the contents of the hiera data documents. Other than that there is no way to dump whole hiera or facts. You need to know the name of the value you are looking for. Then you just run `hiera <variable name>` or `lookup <variable name>` for hiera data and `facter <variable name>` for OS facts. Not sure how much usable this will be in future though, because those are Puppet specific tools, which I suppose go away once also TripleO will be Ansible only.

**Comment by mgirgisf** [comment]
I'm not sure if this the reason you are ask for a way to dump all the tripleo env vars but for me I was testing on standalone env also and I didn't need to dump all the tripleo env vars to stdout I only needed to run 
(export OS_CLOUD=standalone) 

and yes for testing on standalone env we need to have in test_params.yaml 
prometheus_remote_write: ['http://{machine_IP}}']
prometheus_destination : standalone

**Comment by leifmadsen** [comment]
> I'm not sure if this the reason you are ask for a way to dump all the tripleo env vars but for me I was testing on standalone env also and I didn't need to dump all the tripleo env vars to stdout I only needed to run (export OS_CLOUD=standalone)
> 
> and yes for testing on standalone env we need to have in test_params.yaml prometheus_remote_write: ['http://{machine_IP}}'] prometheus_destination : standalone



> > @paramite you mention in PR 1 that a way to dump all the tripleo env vars to stdout(?) is possible.
> 
> You can run `grep -r '*' /etc/puppet/hieradata/` to get the contents of the hiera data documents. Other than that there is no way to dump whole hiera or facts. You need to know the name of the value you are looking for. Then you just run `hiera <variable name>` or `lookup <variable name>` for hiera data and `facter <variable name>` for OS facts. Not sure how much usable this will be in future though, because those are Puppet specific tools, which I suppose go away once also TripleO will be Ansible only.

I was only interested as there was a note somewhere (that I can't find now...) stating there was functionality to dump all the available parameters seen by hiera. It's not a high priority, and seems that it doesn't work quite like I'm describing, so all good there. Sounds like no need to write any documentation around that. Thanks for the info.

**Comment by leifmadsen** [comment]
This has sat here long enough, and Chris has updated the branch with his changes from his branch, and I'd prefer not to let this get so stale that it falls behind that I'm probably going to just force merge this down 🤠.

Please feel free to review after that and then provide updates or file issues to address this.

**Pull request merged**
